import base64

code_str= "ZGVmIGdldF9wcl9pbmZvKHJlcG9fdXJsLCBwcl9udW1iZXIsIGdpdGh1Yl90\nb2tlbik6CiAgICAiIiIKICAgIEEgZHVtbXkgZnVuY3Rpb24gdGhhdCByZXR1\ncm5zIGR1bW15IGRhdGEKICAgICIiIgogICAgcmV0dXJuIHsKICAgICAgICAn\ndGl0bGUnOiAnRHVtbXkgUFIgdGl0bGUnLAogICAgICAgICdib2R5JzogJ0R1\nbW15IFBSIGJvZHknLAogICAgICAgICdhdXRob3InOiAnRHVtbXkgYXV0aG9y\nJywKICAgICAgICAnbGFiZWxzJzogWydkdW1teS1sYWJlbCddLAogICAgICAg\nICdzdGF0ZSc6ICdvcGVuJwogICAgfQo=\n"



print(base64.b64decode(code_str).decode())

